---
title: "Distinctiveness in Two Mode Networks"
author: "Omar Lizardo"
date: "`r Sys.Date()`"
---


# Setup
```{r setup}
   knitr::opts_chunk$set(include = TRUE, 
                       echo = FALSE, 
                       warning = FALSE, 
                       message = FALSE)
   require(here)
   require(kableExtra)
```

# Data
```{r Southern women data}
    A <- matrix(
         c(
          1, 1, 1, 1, 1,  1, 0, 1, 1,  0, 0, 0, 0, 0, 
          1, 1, 1, 0, 1,  1, 1, 1, 0,  0, 0, 0, 0, 0, 
          0, 1, 1, 1, 1,  1, 1, 1, 1,  0, 0, 0, 0, 0, 
          1, 0, 1, 1, 1,  1, 1, 1, 0,  0, 0, 0, 0, 0, 
          0, 0, 1, 1, 1,  0, 1, 0, 0,  0, 0, 0, 0, 0, 
          0, 0, 1, 1, 1,  1, 0, 1, 0,  0, 0, 0, 0, 0, 
          0, 0, 0, 1, 1,  1, 1, 1, 0,  0, 0, 0, 0, 0, 
          0, 0, 0, 1, 1,  0, 1, 1, 1,  0, 0, 0, 0, 0, 
          
          0, 0, 0, 0, 0,  0, 1, 1, 1,  0, 0, 1, 0, 0, 
          0, 0, 0, 0, 0,  0, 0, 1, 1,  1, 0, 1, 0, 0, 
          0, 0, 0, 0, 0,  0, 0, 1, 1,  1, 0, 1, 1, 1,
          0, 0, 0, 0, 0,  0, 1, 1, 1,  1, 0, 1, 1, 1,
          0, 0, 0, 0, 0,  0, 1, 0, 1,  1, 1, 1, 1, 1,
          0, 0, 0, 0, 0,  0, 1, 1, 0,  1, 1, 1, 0, 0,
          0, 0, 0, 0, 0,  0, 0, 0, 1,  0, 1, 0, 0, 0,
          0, 0, 0, 0, 0,  0, 0, 0, 1,  0, 1, 0, 0, 0, 
          
          0, 0, 0, 0, 0,  1, 0, 1, 1,  0, 0, 0, 0, 0,
          0, 0, 0, 0, 0,  0, 0, 1, 1,  0, 0, 0, 0, 0),
          ncol = 14, byrow = TRUE)
     p <- c("EVELYN", "LAURA", "THERESA", "BRENDA", "CHARLOTTE", "FRANCES", "ELEANOR", "RUTH", "VERNE", "MYRA", "KATHERINE", "SYLVIA", "NORA", "HELEN", "OLIVIA", "FLORA", "PEARL", "DOROTHY")
     p.abv <- c("EV", "LA", "TH", "BR", "CH", "FR", "EL", "RU", "VE", "MY", "KA", "SY", "NO", "HE", "OL", "FL", "PE", "DO")
     g <- paste("E", c(1:14), sep = "")
     rownames(A) <- p
     colnames(A) <- g
```

# Matrices
```{r}
   B <- +(!A)
   Bp <- A %*% t(B)
   Bg <- t(t(B) %*% A)
   Bp.n <- solve(diag(rowSums(A))) %*% Bp
   Bg.n <- solve(diag(colSums(A))) %*% Bg
   rownames(Bp.n) <- p
   rownames(Bg.n) <- g
   Cp <- as.matrix(sort(rowSums(Bp.n), decreasing = T)/nrow(A))
   colnames(Cp) <- c("Distinctiveness")
   Cg <- as.matrix(sort(rowSums(Bg.n), decreasing = T)/ncol(A))
   colnames(Cg) <- c("Distinctiveness")
   #rownames(Bp) <- w.abv
   #colnames(Bp) <- w.abv 
   #rownames(Dp) <- w.abv
   #colnames(Dp) <- w.abv 
```

# Tables
```{r}
   make.table <- function(t, c = "", fn, ang = 0) {
      kbl(t, format = "latex", booktabs = T, 
          linesep = "", caption = c, digits = 2) %>%
         kable_styling(latex_options = c("hold_position")) %>% 
         row_spec(0, angle = ang) %>% 
         save_kable(here("Tabs", paste(fn, ".tex", sep = "")))
         }
   make.scale.table <- function(t, c = "", fn, ang = 0) {
      kbl(t, format = "latex", booktabs = T, 
          linesep = "", caption = c, digits = 2) %>%
         kable_styling(latex_options = c("hold_position", "scale_down")) %>% 
         row_spec(0, angle = ang) %>% 
         save_kable(here("Tabs", paste(fn, ".tex", sep = "")))
         }

   make.table(A, cap = "\\label{tab:sw}", fn = "sw")
   make.table(Bp, cap = "\\label{tab:Bp}", fn = "Bp", ang = -90)
   make.table(Bg, cap = "\\label{tab:Bg}", fn = "Bg")
   make.scale.table(Bp.n, cap = "\\label{tab:Bpn}", fn = "Bpn", ang = -90)
   make.table(Bg.n, cap = "\\label{tab:Bgn}", fn = "Bgn")
   make.table(Cp, cap = "\\label{tab:Cp}", fn = "CDp")
   make.table(Cg, cap = "\\label{tab:Cg}", fn = "CDg")
```

`



